[saved-setup]
[labels]
title="Normal" x/y Cartesian Coordinate Graphs, Including Relations
left=polynomials
right=conic sections

[grid]
left=-8.0000
right=8.0000
top=auto
bottom=auto

[options]
labels=on

[equations]
y=1/2x+3 ' linear function
y=1/3x^3 ' cubic
y=1/x ' hyperbola
x^2 + y^2 = 25 ' circle around origin radius 5
x^2/36 + y^2/9 = 1 ' ellipse 6 x 3
y=x^2 ' standard parabola
x=y^2 ' "sideways" parabola
